// Code generated by github.com/borderlesshq/genqlient, DO NOT EDIT.

package main

import (
	"context"
	"time"

	"github.com/borderlesshq/genqlient/graphql"
)

// GetUserResponse is returned by getUser on success.
type GetUserResponse struct {
	// Lookup a user by login.
	User getUserUser `json:"user,omitempty"`
}

// GetUser returns GetUserResponse.User, and is useful for accessing the field via an interface.
func (v *GetUserResponse) GetUser() getUserUser { return v.User }

// GetViewerResponse is returned by getViewer on success.
type GetViewerResponse struct {
	// The currently authenticated user.
	Viewer getViewerViewerUser `json:"viewer,omitempty"`
}

// GetViewer returns GetViewerResponse.Viewer, and is useful for accessing the field via an interface.
func (v *GetViewerResponse) GetViewer() getViewerViewerUser { return v.Viewer }

// __getUserInput is used internally by genqlient
type __getUserInput struct {
	Login string `json:"Login,omitempty"`
}

// GetLogin returns __getUserInput.Login, and is useful for accessing the field via an interface.
func (v *__getUserInput) GetLogin() string { return v.Login }

// getUserUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user is an individual's account on GitHub that owns repositories and can make new content.
type getUserUser struct {
	// The user's public profile name.
	TheirName string `json:"theirName,omitempty"`
	// Identifies the date and time when the object was created.
	CreatedAt time.Time `json:"createdAt,omitempty"`
}

// GetTheirName returns getUserUser.TheirName, and is useful for accessing the field via an interface.
func (v *getUserUser) GetTheirName() string { return v.TheirName }

// GetCreatedAt returns getUserUser.CreatedAt, and is useful for accessing the field via an interface.
func (v *getUserUser) GetCreatedAt() time.Time { return v.CreatedAt }

// getViewerViewerUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user is an individual's account on GitHub that owns repositories and can make new content.
type getViewerViewerUser struct {
	// The user's public profile name.
	MyName string `json:"MyName,omitempty"`
	// Identifies the date and time when the object was created.
	CreatedAt time.Time `json:"createdAt,omitempty"`
}

// GetMyName returns getViewerViewerUser.MyName, and is useful for accessing the field via an interface.
func (v *getViewerViewerUser) GetMyName() string { return v.MyName }

// GetCreatedAt returns getViewerViewerUser.CreatedAt, and is useful for accessing the field via an interface.
func (v *getViewerViewerUser) GetCreatedAt() time.Time { return v.CreatedAt }

// The query or mutation executed by getUser.
const getUser_Operation = `
query getUser ($Login: String!) {
	user(login: $Login) {
		theirName: name
		createdAt
	}
}
`

// getUser gets the given user's name from their username.
func getUser(
	ctx context.Context,
	client graphql.Client,
	Login string,
) (*GetUserResponse, error) {
	req := &graphql.Request{
		OpName: "getUser",
		Query:  getUser_Operation,
		Variables: &__getUserInput{
			Login: Login,
		},
	}
	var err error

	var data GetUserResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getViewer.
const getViewer_Operation = `
query getViewer {
	viewer {
		MyName: name
		createdAt
	}
}
`

func getViewer(
	ctx context.Context,
	client graphql.Client,
) (*GetViewerResponse, error) {
	req := &graphql.Request{
		OpName: "getViewer",
		Query:  getViewer_Operation,
	}
	var err error

	var data GetViewerResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
